name: unicore-mama-sbm
user: ubuntu
buildscript: sideloader/deploy.sh
postinstall: sideloader/postinstall.sh
pip:
 - gunicorn
 - pyramid
 - pyramid_chameleon
 - pyramid_debugtoolbar
 - pyramid_tm
 - SQLAlchemy
 - transaction
 - zope.sqlalchemy
 - waitress
dependencies:
 - python-yaml
