"""add message_profile join field

Revision ID: 1c89d076746b
Revises: 18b7e31bc9ed
Create Date: 2014-06-30 14:58:32.839354

"""

# revision identifiers, used by Alembic.
revision = '1c89d076746b'
down_revision = '18b7e31bc9ed'

from alembic import op
import sqlalchemy as sa
from mamasbm.models import UUID


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'messages', sa.Column('message_profile_id', UUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_profile_id')
    ### end Alembic commands ###
