"""add send_day to message profile

Revision ID: 1c9e829abd8e
Revises: 29fb24fdc151
Create Date: 2014-07-16 14:23:04.006251

"""

# revision identifiers, used by Alembic.
revision = '1c9e829abd8e'
down_revision = '29fb24fdc151'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'message_profiles', sa.Column('send_day', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_profiles', 'send_day')
    ### end Alembic commands ###
