"""add profiles table

Revision ID: 40e18b7ea943
Revises: 153e40ee69e2
Create Date: 2014-06-20 16:02:17.471034

"""

# revision identifiers, used by Alembic.
revision = '40e18b7ea943'
down_revision = '153e40ee69e2'

from alembic import op
import sqlalchemy as sa
from mamasbm.models import UUID


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profiles',
        sa.Column('uuid', UUID(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('num_messages_pre', sa.Integer(), nullable=True),
        sa.Column('num_messages_post', sa.Integer(), nullable=True),
        sa.Column('send_days', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    ### end Alembic commands ###
